// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB07Ftle4q3maRzdp6EgdZqxffuP_Y3Q-A',
    appId: '1:893211332380:android:a923caf7f0cab8707ff4d9',
    messagingSenderId: '893211332380',
    projectId: 'dummy',
    databaseURL: 'https://dummy-default-rtdb.firebaseio.com',
    storageBucket: 'dummy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxv7IvnoqSRcpzZpbYt0lagM7VN-nzJ7E',
    appId: '1:893211332380:ios:51b85d71fa2e2dfe7ff4d9',
    messagingSenderId: '893211332380',
    projectId: 'dummy',
    databaseURL: 'https://dummy-default-rtdb.firebaseio.com',
    storageBucket: 'dummy.appspot.com',
    iosClientId: '893211332380-e45i09n9cr0ppecevttdij540c4alejh.apps.googleusercontent.com',
    iosBundleId: 'com.oculus.techrace',
  );
}
