//todo this will be auto generated by FlutterFire CLI
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'dummy',
    appId: '1:dummy:android:2bf759793a9f22097ff4d9',
    messagingSenderId: '893211332380',
    projectId: 'dummy',
    databaseURL: 'https://dummy-default-rtdb.firebaseio.com',
    storageBucket: 'dummy.dummy.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'dummy',
    appId: '1:893211332380:ios:0ead96e61a4d41d77ff4d9',
    messagingSenderId: '893211332380',
    projectId: 'dummy',
    databaseURL: 'https://dummy-default-rtdb.firebaseio.com',
    storageBucket: 'dummy.appspot.com',
    iosClientId: 'dummy-g7opjar3uhjqcg10d1llocqr9cd49uvo.apps.googleusercontent.com',
    iosBundleId: 'com.dummy.dummy.dummy',
  );
}
